### PR TITLE
Provide the DE sampler with a seed.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Review by dawsoneliasen — APPROVED** [review]

**Comment by bangerth** [comment]
@dawsoneliasen I'll let you merge if you're ok with this change -- it's time to get you to review and merge patches as well :-)

**Comment by bangerth** [comment]
@dawsoneliasen  Do you see the big green merge button?

**Comment by dawsoneliasen** [comment]
@bangerth Sorry for the delay, looked at this before I had the write access. Will do!

**Comment by bangerth** [comment]
Yay, now two people have write access :-)

General rule: Never write to the master branch, do everything via pull requests.

**Pull request merged**
