### PR TITLE
Use () instead of [] for Eigen vectors.

### PR DESCRIPTION
**Pull request by dklong-csu**

### CODE REVIEW

**Comment by dklong-csu** [comment]
Strange. Locally, I'm having covariance_matrix_11 fail and adaptive_mh_01 pass. Yet the check here is showing the opposite.

**Comment by bangerth** [comment]
Your changes are not based on the current master branch, and there are conflicts. Can you rebase and resolve the conflicts? We'll see what then happens to the test failures.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
There is a failing test, but it may also be due to a merge conflict. Can you rebase to master?

Apologies for not noticing this PR for so long...

**Comment by dklong-csu** [comment]
I tried rebasing a while ago and something was still weird. Then this fell off my radar for a bit. I'll try again later today and see if I can fix the issues.

**Comment by dklong-csu** [comment]
The one check failing puzzles me. If I revert back to square brackets, I get the exact same results as with parentheses -- i.e. it still fails.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Same as in #172, this just shows that we probably merged something that didn't pass the test suite :-( But that is unrelated to this current PR.

**Pull request merged**
