### PR TITLE
Add a producer for samples given as a range of objects.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by bangerth** [comment]
@MantautasRimkus -- you might be interested in this. Click on the "Files changed" link above to see the changes I made. The documentation of the class has examples of how this can be used.

**Comment by MantautasRimkus** [comment]
So let me know if I'm right (to check if I understood correctly): 
Does that mean, that we gonna pass vector element with known values and this class gonna produce "samples", which would be just every element of that vector? 
Does that mean that we would know what results we should expect if we connect a consumer to this producer from Range Class?

**Comment by bangerth** [comment]
Yes, that's exactly right. I'm going to send you an email later today in which I'll tell you about the testing framework I've written in #4. It shows how to use this `Range` class to produce a known sequence of samples for which I can compute by hand what the mean, standard deviation, last sample, etc, all are. And then I can compare with what the classes that implement these things compute to convince myself that they are right!

**Comment by MantautasRimkus** [comment]
Can't wait to see it. I hope that everything gonna be right.

**Pull request merged**
